### PR TITLE
Revert LibStub removal (need more investigations & fixes)

### PR DESCRIPTION
**Pull request by MysteryDragon**
Hey, @Sharlikran !

I carefully reverted the part about adding LibStub, because when I disabled every addon expect RaidNotifier and its dependencies, the error popped up:
cannot_apply_libtitlelocale

The reason as I believe is that some other addon provided LibStub that was being used by RaidNotifier, while you tested it.

Italy language, adjustments for other languages, indentation fixes, and even some version adjustments aren't reverted and going to be deployed soon.

As for LibStub, it seems that further work is needed.
Thankfully it'd be easier for you (or me) to revert this commit back to continue the work on it, so it should not come as big issue.

Not sure when I'll have time to try to adjust it the way that it'd work.
You're welcome to try if you have time, and make another PR 🙌 

Cannot promise fast merging, will have to test it, and I'm so out of time usually 😔 

I think that it shall be done this way:
- LibCustomTitles should check if LibStub is presented (like LibAddonMenu does it, for instance) - this way it'll go fine with intergration with other addons if they still use it
- In case LibStub isn't presented, it should still show custom titles for the persons that are listed in related lua files 🤷‍♂️ But no synchronization will be provided (that sounds reasonable - we cannot rely on LibStub if every participant got rid of LibStub 😁)

Otherwise I find it difficult to name it as non-breaking change 😔

### CODE REVIEW

**Comment by MysteryDragon** [comment]
And thanks again for your time and your efforts to make RaidNotifier better, it is much appretiated 🙌

**Comment by MysteryDragon** [comment]
@Sharlikran and another case is LibGroupSocket as requirement.
I do believe we should stick with optional dependency, and adjust the code accordingly. I didn't have it, and it was totally fine for me in terms of usage (as I didn't use this part of the functional).
Also, it is complicated to detect if any addon has new dependency, sadly Minion is unable to handle it on its own. So a lot of players will be confused.

**Comment by Sharlikran** [comment]
Users won't be confused. That's not a thing. Many users see the red text for missing libraries and know how to installed them.

It's not really testing that made it work. I don't have LibStub installed at all. None of my mods use it and I remove it from everything I have installed.

By reverting everything you hacked the code back together in a way the requires LibStub again.

So never mind.

Some people in my guild hate this tool and I removed LibStub because I don't dislike RN, I just don't do trials. They were happy with it because it functioned properly without LibStub, which of course because of my changes.

**Comment by MysteryDragon** [comment]
Hey again, @Sharlikran !

> Users won't be confused. That's not a thing. Many users see the red text for missing libraries and know how to installed them. People will sometimes complain about the new library requirement not being in the change log or on the description page, but they are just whining. When people whine they are just doing so because of their poor character.

Well, that's good that you have such guildies (right?) 😁 
People in the guild I'm part of are not that smart (sometimes, not always of course).
I'm speaking from my experience 😔 
And tbh I cannot blame them, it feels natural that the addon manager would handle such things itself. Hoping that Minion will get such upgrade once.

> By reverting everything you hacked the code back together in a way the requires LibStub again.

Not really hacking, I just used "git revert" with commiting part of the changes. So I put it in previous state, but only for the parts which were about LibStub (or roughly about it).

The reason again is that the addon won't work in the previous state, unfortunately.

I just have no time for now to test the adjustments that would be needed.
But I think that I'll return to it one day, and most likely your proposal will come as base (again, `git revert` will help me 🙌 ). Do not think they are just erased, because Git remembers everything ;)

> I'm not looking to maintain the mod. The fact you have figured out how to add new features is great. I admire you for that. Keep up the good work.

Sure, of course! Thanks for your contributing! And as I said, it is likely that it is not the end, and your remaining changes will go life, but with some little fixes.

**Pull request merged**
