### PR TITLE
Add Italian, remove LibStub

### PR DESCRIPTION
**Pull request by Sharlikran**
@MysteryDragon Not sure if you are interested. This adds Italian (I don't speak it), removes LibStub, and gets rid of some trailing spaces. It also synchronizes the language files so there are no missing strings for someone that wishes to update them.

### CODE REVIEW

**Comment by Sharlikran** [comment]
> Btw it's not working that well unfortunately, some initialization error pops up. Looks like some sort of incorrect order of loading the addons, but I'm not sure. When I'll have time, I'll investigate the reasons and will be able to fix them.

This is not an issue with this version. All libraries need a manifest file so that is provided for LibCSA and LibUnits2. In addition to that LibGroupSocket is required, not optional. I didn't make any changes that would affect that and make it a requirement. Users will need sirinsidiator's plugin.

**Comment by MysteryDragon** [comment]
Hey, @Sharlikran !

Thanks for your time and your PR!

I'm interested in making RaidNotifier better, but unfortunately lacking time a lot 😔 
That's why the process is going extremely slow, if it's going at all.

While I find it useful to finally get rid of LibStub, and I don't mind adding Italian, there are also changes that removes this LibCustomTitles, which I cannot merge because I promised to keep existing functional to memus, so it doesn't feel right to go from my word now.
I do understand that a lot of addon maintainters dislike this, but I'm simply not the proper owner to set my rules.

We can declare it explicitly (add txt file for LibCustomTitles), and then those who dislikes it could just disable it, I think 🤷‍♂️ 
But not sure if I can propose more than that.

**Comment by Sharlikran** [comment]
@MysteryDragon I understand your point but the version provided with Raid Notifier is outdated. Even `Dolgubon's Lazy Writ Crafter` and `Dolgubon's Lazy Set (and Furniture!) Crafter` do not package it with their mods when Dolgubon is sort of the current maintainer.

It doesn't make a lot of sense to provide a library that registers "LibCustomTitlesRN" with LibStub while Dolgubon's registers "LibCustomTitles". That's not even taking advantage of the LibStub functionality. If @Kyoma and Dolgubon want to get together and combine them and make an update, then if that were provided that would be different.

**Review by MysteryDragon — APPROVED** [review]

**Comment by MysteryDragon** [comment]
Hey, @Sharlikran !
Sorry for keeping you waiting, I'm quite occupied during weekdays 😔 

I shall check the situation around LibCustomTitles in `Dolgubon's Lazy Writ Crafter` and `Dolgubon's Lazy Set (and Furniture!) Crafter`, when I'll have time.

As I see it there is LibStub in `Dolgubon's Lazy Writ Crafter`.

So in case it will break anything, we might need to revert the changes.
Will see how it goes.

I'm going to make sure it works, and then I'll deploy the update.

**Comment by MysteryDragon** [comment]
@Sharlikran right now, as I see it, LibCustomTitles from RaidNotifier won't work without LibStub at all, that doesn't look right.
If we removed what worked, we'll have to bring it back.
But as I told you I'm going to test it, maybe I'm mistaken.

**Pull request merged**
