### PR TITLE
Extend /rnulti command for more options

### PR DESCRIPTION
**Pull request by memus**
Because rnulti command already exist. This command gives everyone possibillity to quick change settings so i extened rnulti for few new things:
/rnulti show [dps|heal|tank]
/rnulti cost <override_utlimate_cost>

### CODE REVIEW

**Comment by kyoma** [comment]
Hey, the ulti cost is definitely useful but I'm not sure if things like role switching is really needed through command line. I'll look at it later today as I'm also gonna update /rndebug with some things.

**Comment by memus** [comment]
Sometimes when i need to go with a pug run/help it might be helpful to just say "type in chat /rnulti show heal tank" without waiting when he/she will find that in group settings.
That was helpful when you first provided /rnulti hidden command.
"guys just type /rnulti enable"

**Comment by memus** [comment]
And i am thinkig about something like /rnulti cost auto so it would take current bar ultimate cost

**Comment by memus** [comment]
Theres gonna be another pull request without role switching

**Pull request closed without merging**
