### PR TITLE
Memus repository version plus gradual per-commit update to actual version (2.15)

### PR DESCRIPTION
**Pull request by MysteryDragon**
Greetings, @kyoma!

Let me apologize for bothering you as I know that you don't play ESO so often nowadays and declared that RaidNotifier will not receive any updates except UI fixes.
I think that RaidNotifier is great tool and would like to try to help you with some updates. I don't play much, but it seems that I'll not abandon this game in the near future, so maybe I'll be able to extend life of this awesome addon in which you and other authors putted so much effort.

I wrote you PM at esoui.com but seems you didn't see it, so I decided to make PR here. Sorry if it's not applicable.

This PR is pretty straightforward: I took @memus version of your addon since it's more updated one, then made several per-version commits to update project state to actual 2.15 version.

You can easily check now by `diff` command or somehow else that this version have no differences with actual one at esoui.com.

The reason to apply this pull request is to be able to open more pull requests with actual proposals that you'll be able to review, comment and decide their fate.

My current plan for future requests is (_each feature in it's own PR with small code changes, should be not too complicated to review them_):
- Maw of Lorkhaj Hulk debuff notification
- Fix Zhaj'hassa's cleansing platforms error report when setting it up
- Add some (just some) Kyne's Aegis notifications
- Make "custom" announcement type movable
- Fix (more, fix more! :D) that issue with displaying `#...` instead of player name in certain circumstances
- Eradicate LibStub in code
- Expose LibCSA, LibCustomTitles and LibTitleLocale (debatable)

This changes I have prepared already since this is common requests from players (including my guild), and will send you these pull requests if you'll decide to accept this one (since this is basic).
For now I'm playing with all this changes and testing how it works (so far so good :D).

Thanks for attention!

### CODE REVIEW

**Comment by MysteryDragon** [comment]
@memus oh my, that was insanely quick reaction :O
At first I thought to open this PR towards your fork, but to be honest I was doubted that you'll see that since last updates were uploaded solely by Kyoma.
But since you keep tracking stuff here, I'd like to ask you, which repository should I prefer to open new pull requests for mentioned updates? Which one would be more convenient, this one, or your fork?

And thank you for accepting PR!

**Comment by memus** [comment]
My bad because i thought you forgot about last kyoma changes so i append his changes from esoui. But then i realized that you did it in your pull request ;)

**Comment by MysteryDragon** [comment]
No, it's fine! Don't worry :D
I mean that I have some _new_ features / fixes that I'd like to propose as new pull requests (not really much code in each), and I wonder should I open new pull requests here or at https://github.com/memus/ESO-RaidNotifier ?

**Comment by memus** [comment]
@MysteryDragon doesn't matter.

**Pull request merged**
