### PR TITLE
Added sphere spawn, 'Gusts Of Steam' and fire on execute phase

### PR DESCRIPTION
**Pull request by memus**
Today i am going to test it.

### CODE REVIEW

**Comment by kyoma** [comment]
Do you happen to know if the sphere spawning provides the unitId when it occurs?

Oh and after seeing the jump/gust in action I think it would be better to just have a single notification when it starts, seeing as the gusts and eruptions are basically always the same.

**Comment by memus** [comment]
> Do you happen to know if the sphere spawning provides the unitId when it occurs?
Forgot to add dbg for that so no idea.

> after seeing the jump/gust in action I think it would be better to just have a single notification when it starts, seeing as the gusts and eruptions are basically always the same.
True i was thinkig what to do with that.

There is one problem with trial by fire. Can you check it out? I think that was something with dbg() because with execute phase i had lua error but there was no time to check that out and i forgot to take a screenshot :)

**Comment by kyoma** [comment]
I'm gonna merge this and make a few tweaks for when I go in tonight. Only weekly tho so can't test my boss code.

**Comment by memus** [comment]
I'll merge hour changes today and test it tonight :)

**Pull request merged**
